#!/bin/bash

# enable bash debug by remove the comment for set -xv
# set -xv

year=`date +%Y`
mont=`date +%m`
days=`date +%d`
date=$mont$days$year


function help() {
 echo "if no argument provided, default file list name is src.f and default target directory is ../rtl"
 echo "Usage:"
 echo "   gen_rtl src_another.f target_dir"
}



# $1 source file list
# $2 target directory
function cp_file_list() {
  # echo "enter cp_file_list()"  
  rtld=`pwd`
  # echo "pwd = rtld = $rtld"
  src_fl=$1
  trg_dr=$2
  # echo "src_fl = $src_fl"
  # echo "trg_dr = $trg_dr"
  # enter_flag=0
  # echo "init enter_flag = $enter_flag"
  while read -r line || [ -n "$line" ]
  do
    # enter_flag=1
    # echo "set enter_flag = $enter_flag"
    # echo $line
    if [[ "$line" =~ ^\s*\/\/ ]] ; then
      # echo "line include //"
      continue
    fi

    if [ "$line" == "" ] ; then
      # echo "line is empty"
      continue
    fi

    if [[ "$line" =~ '-f' ]]; then
    # echo "Found -f"
      flst=`echo $line | sed -e 's/-f//'`
      if [ ! -f $flst ]; then
        curd=`pwd`
        echo "Filelist: $flst not exist at $curd"
        exit 1
      fi

      dos2unix $flst
 
      # echo "===="
      dirn=`dirname $flst`
      filn=`basename $flst`
      rtld=`pwd`
      # echo "flst = $flst"
      # echo "dirn = $dirn"
      # echo "filn = $filn"
      # echo "pwd = rtld = $rtld"
      # echo "run cp_file_list $filn $trg_dr"
      pushd . > /dev/null ; cd $dirn ; cp_file_list $filn $trg_dr ; popd > /dev/null
      # echo "===="
    else
      if [ ! -e $line ]; then
        echo "File: $line not exist"
        exit 1
      fi
      # echo "Not Found -f"
      # src=`eval echo $line`
      # echo $line
      src=`eval echo $line`
      curd=`pwd`
      # echo $src $curd
      if [ ! -f $src ]; then
        # echo "+++++++"
        # echo $line
        curd=`pwd`
        # echo $src
        # ls -al
        # ls $src
        # ls $line
        echo "File: $src not exist at $curd"
        echo -n "File: "
        echo -n $src
        echo " not exist at $curd"
        echo "+++++++"
        exit 1
      fi
      # echo $src
      # echo "++++++++++++++"
      srf=`basename $src`
      # echo $srf
      # echo "++++++++++++++"
      # echo "cp -f $src $trg_dr"
      cp -f $src $trg_dr
      # curd=`pwd`
      # echo "++++++++++++++"
      # ls -al $src
      # echo "$curd"
      # echo "++++++++++++++"
      #+ do post-processing here
      sed -i -e "/Release/s/MMDDYYYY/$date/"  $trg_dr/$srf
    # sed -i -e "/default_nettype/s/^/\/\/ /" $trg_dr/$srf
      #- do post-processing here
      chmod 0444 $trg_dr/$srf
    fi
  done < $src_fl
  # echo "check enter_flag = $enter_flag"
  # if [ $enter_flag == 0 ]; then
  #   echo "detect enter_flag = 0"
  #   exit 1
  # fi
  # echo "exit cp_file_list()"  
}




if [ $# -lt 1 ]; then
  # default source file list and target folder
  srcf=src.f
  tdir=../rtl
  # make a real copy to the "../dsn/rtl" directory
  if [ ! -e $tdir ]; then
    mkdir $tdir
  fi
else
  if [[ "$1" =~ '-h' ]]; then
    help
    exit 1
  else
    srcf=$1
    tdir=$2
    dirn=`dirname  $srcf`
    fnam=`basename $srcf`
    cd $dirn
    pwd
#   if [ "$dirn" != "." ]; then
#     echo "source file can only be local"
#     exit 1
#   fi
  fi
fi

# if [ ! -f $srcf ]; then
if [ -f $fnam ]; then
  srcf=$fnam
else
  echo "File: $srcf not exist"
  exit 1
fi


# -----------------------------------------------
# remove comment out file
# src_f=`cat $srcf | sed -e '/\/\//d ; s/-v//'`

# echo $srcf
# echo "====================================="


while read -r line || [ -n "$line" ]
do
# echo "-------------------------------------"
# echo $line
# echo $line | grep '^\s*\/\/'
# status=$?
# echo $status
# if [ $status -eq 0 ]; then
#   echo "//"
# fi
  if [[ "$line" =~ ^\s*\/\/ ]] ; then
  # echo "+++++++++++++"
    continue
  fi

  if [ "$line" == "" ] ; then
    continue
  fi



# else
#   echo "\\\\"
# fi

# echo "=============="

# echo $line | grep '\-f'
# status=$?
# echo $status
# if [ $status -eq 0 ]; then
  if [[ "$line" =~ '-f' ]]; then
  # echo "Found -f"
    flst=`echo $line | sed -e 's/-f//'`
  # echo "===="

    if [ ! -f $flst ]; then
      curd=`pwd`
      echo "Filelist: $flst not exist at $curd"
      exit 1
    fi

    dos2unix $flst

    dirn=`dirname $flst`
  # echo $flst
    filn=`basename $flst`
  # echo $dirn 
    # check absolute path of target path
    if [[ "$tdir" =~ ^/.* ]]; then
      rtld=$tdir
    else
      rtld=`pwd`
      rtld=$rtld/$tdir
    fi
  # pushd . > /dev/null ; cd $dirn ; cp_file_list $filn $rtld/$tdir ; popd > /dev/null
    pushd . > /dev/null ; cd $dirn ; cp_file_list $filn $rtld       ; popd > /dev/null
  # echo "===="
  else
  # if [ ! -f $line ]; then
  #   echo "File: $line not exist"
  #   exit 1
  # fi
  # echo "Not Found -f"
    src=`eval echo $line`
    if [ ! -f $src ]; then
      curd=`pwd`
      echo "File: $src not exist at $curd"
      exit 1
    fi
  # echo $src
  # echo "---------"
    srf=`basename $src`
  # echo "---------"
  # echo $srf
    cp -f $src $tdir
    #+ do post-processing here
    sed -i -e "/Release/s/MMDDYYYY/$date/"  $tdir/$srf
  # sed -i -e "/default_nettype/s/^/\/\/ /" $tdir/$srf
    #- do post-processing here
    chmod 0444 $tdir/$srf
  fi

# src=`eval echo $line`
# echo $src
# srf=`basename $src`
# echo $srf

done < $srcf


echo Release Date: $mont $days
